cclient:p3-dogClient.c
	gcc p3-dogClient.c -o client
cserver:p3-dogServer.c
	gcc p3-dogServer.c -o server -lpthread
crand:generateRandom.c
	gcc generateRandom.c -o random
eclient:p3-dogClient.c
	./client 127.0.0.1
eserver:p3-dogServer.c
	./server
erand:generateRandom.c
	./random
